In [3]:
import numpy as np
print("Hello")

Hello


In [4]:
import numpy as np
print(np.__version__)

2.4.2


In [11]:
X = np.arange(10)
Y =np.array([2,3,4,5])
print(X)
print(Y)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]


In [12]:
 #Solution
np.full((3,3), True, dtype=bool)

#or
np.full((9), True, dtype=bool).reshape(3,3)

#or
np.ones((3,3), dtype=bool)

#or
np.ones((9), dtype=bool).reshape(3,3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print('Modified Array')
print(out)

print('\nOriginal Array')
arr


Modified Array
[ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# Question: Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
# Question: Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [19]:
# Question: From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [20]:
# Question: Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [21]:
# Question: Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a >= 5) & (a <= 10)]


array([ 6,  9, 10])

In [22]:
# Question: Convert the function maxx that works on two scalars, to work on two arrays.

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    

def pair_max(x, y):
    # here I am using map to make tuple from a and b, other solution is using zip(a,b)
    maximum = [maxx(a,b) for a,b in map(lambda a,b:(a,b),x,y)]
    # using zip
    # maximum = [maxx(a,b) for a,b in zip(x,y)]
    return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)    

array([6, 7, 9, 8, 9, 7, 5])

In [25]:
# Question: Reverse the rows of a 2D array arr.

arr = np.arange(9).reshape(3,3)

print('Original array')
print(arr)


# Solution

print("\nModified array")
arr[::-1, :]

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [27]:
# Question: Find the mean, median, standard deviation of iris's sepallength (1st column)

#iris_data = np.genfromtxt('../input/iris/Iris.csv', delimiter=',', skip_header=1, usecols = [1])
arr=np.array([1,2,3,4,5,6])
print('Mean', np.mean(arr))
print('Median', np.median(arr))
print('Standard Deviation', np.std(arr))

Mean 3.5
Median 3.5
Standard Deviation 1.707825127659933
